# Ansible Variables for Tripr App Deployment
# This file centralizes all variables used across the playbooks

# Application Configuration
app_name: "{{ lookup('env', 'ANSIBLE_APP_NAME') }}"
app_replicas: "{{ lookup('env', 'ANSIBLE_K3S_REPLICAS') | default('2') }}"
app_port: "{{ lookup('env', 'ANSIBLE_K3S_APP_PORT') | default('8080') }}"
docker_image: "{{ lookup('env', 'ANSIBLE_DOCKER_IMAGE') }}"

# Domain and SSL Configuration
app_domain: "{{ lookup('env', 'ANSIBLE_BASE_URL') }}"
cert_manager_email: "valentin.millet39@gmail.com"

# Database Configuration
db_name: "{{ lookup('env', 'ANSIBLE_DB_NAME') }}"
db_user: "{{ lookup('env', 'ANSIBLE_DB_USERNAME') }}"
db_password: "{{ lookup('env', 'ANSIBLE_DB_PASSWORD') }}"
db_host: "{{ lookup('env', 'ANSIBLE_DB_HOST') }}"
db_port: "{{ lookup('env', 'ANSIBLE_DB_PORT') | default('5432') }}"
pg_version: "{{ lookup('env', 'ANSIBLE_PG_VERSION') | default('17') }}"

# Mail Configuration
mail_host: "{{ lookup('env', 'ANSIBLE_MAIL_HOST') }}"
mail_port: "{{ lookup('env', 'ANSIBLE_MAIL_PORT') }}"
mail_username: "{{ lookup('env', 'ANSIBLE_MAIL_USERNAME') }}"
mail_password: "{{ lookup('env', 'ANSIBLE_MAIL_PASSWORD') }}"

# Security Configuration
jwt_secret: "{{ lookup('env', 'ANSIBLE_JWT_SECRET') }}"

# OAuth2 Proxy Configuration for monitoring dashboards
github_oauth_client_id: "{{ lookup('env', 'ANSIBLE_GITHUB_OAUTH_CLIENT_ID') }}"
github_oauth_client_secret: "{{ lookup('env', 'ANSIBLE_GITHUB_OAUTH_CLIENT_SECRET') }}"
oauth2_proxy_cookie_secret: "{{ lookup('env', 'ANSIBLE_OAUTH2_PROXY_COOKIE_SECRET') }}"

# Kubernetes Resource Configuration
k8s_resources:
  requests:
    memory: "500Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "2"

# Health Check Configuration
health_check:
  initial_delay_seconds: 65
  period_seconds: 5
  timeout_seconds: 3
  failure_threshold: 30
  success_threshold: 1

# Liveness Probe Configuration
liveness_probe:
  initial_delay_seconds: 65
  period_seconds: 10
  timeout_seconds: 5
  failure_threshold: 30

# PostgreSQL Configuration
postgresql:
  data_dir: "/etc/postgresql/{{ pg_version }}/main"
  apt_source_check_files:
    - "/etc/apt/sources.list"
    - "/etc/apt/sources.list.d/*"

# K3s Configuration
k3s:
  install_script_url: "https://get.k3s.io"
  api_port: 6443
  wait_timeout: 60

# Cert-manager Configuration
cert_manager:
  version: "v1.17.2"
  manifest_url: "https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.yaml"
  namespace: "cert-manager"
  wait_timeout: 300
