services:
  postgres:
    image: postgres:17.3
    environment:
      - POSTGRES_DB=tripr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssword!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynet

  mailpit:
    image: axllent/mailpit:v1.23
    ports:
      - "1026:1025"  # SMTP server port (changed from 1025 to avoid conflict)
      - "8026:8025"  # Web UI port (changed from 8025 to avoid conflict)
    restart: unless-stopped
    networks:
      - mynet

volumes:
  postgres_data:
networks:
  mynet:
    driver: bridge
