---
- name: Install and setup PostgreSQL
  hosts: all
  become: yes # Exécute les tâches avec les privilèges sudo
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    db_name: trpir
    db_user: postgres
    db_password: VotreMotDePasseSuperSécurisé
    pg_version: 17

  tasks:
    - name: Install postgresql-common to get APT configuration script
      apt:
        name:
          - "postgresql-common"
        state: present

    - name: Check if PostgreSQL APT source is already present
      ansible.builtin.shell: "cat /etc/apt/sources.list /etc/apt/sources.list.d/* | grep -q 'https://apt.postgresql.org'"
      register: pgsql_apt_source_check
      ignore_errors: true
      changed_when: false

    - name: Execute pgdg apt script if PostgreSQL APT source is not found
      ansible.builtin.command: "/usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y"
      when: pgsql_apt_source_check.rc != 0

    - name: Install PostgreSQL and its dependencies
      apt:
        name:
          - "postgresql-{{ pg_version }}"
          - python3-psycopg2 # Required for module community.postgresql.postgresql_user and postgresql_db
        state: present

    - name: Ensure that the PostgreSQL service is started and activated
      systemd:
        name: "postgresql@{{ pg_version }}-main"
        state: started
        enabled: yes

    - name: Create PostgreSQL database
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        state: present
      become_user: postgres

    - name: Create new PostgreSQL user
      community.postgresql.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        state: present
      become_user: postgres

    - name: Grant all database privileges to the user
      community.postgresql.postgresql_privs:
        db: "{{ db_name }}"
        role: "{{ db_user }}"
        privs: ALL
        type: database
      become_user: postgres

    - name: Show success message
      debug:
        msg: "The database '{{ db_name }}' and the user '{{ db_user }}' have been successfully created."
