spring:
  application:
    name: spring-ad-search
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1026}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tripr}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:P4ssword!}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  docker:
    compose:
      enabled: true
      file: compose.yaml

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.adsearch: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# API configuration
api:
  # Comma-separated list of API keys for external services
  # In a real application, these would be stored securely
  keys: dummy-key-1,dummy-key-2,dummy-key-3
  
  # Configuration for external API endpoints
  # These are not used in the mock implementations
  endpoints:
    classifieds: https://api.mockclassifieds.example.com/v1
    marketplace: https://api.mockmarketplace.example.com/v2
    auction: https://api.mockauction.example.com/v1

# JWT configuration
jwt:
  secret: ${JWT_SECRET:verySecretKeyThatShouldBeAtLeast32CharactersLong}
  expiration: 3600000  # 1 hour in milliseconds
  issuer: spring-ad-search
  refresh-token:
    cookie-name: refresh-token
    expiration: 604800000  # 7 days in milliseconds

# Password reset configuration
password-reset:
  token-expiration: 86400000  # 24 hours in milliseconds
  base-url: http://localhost:8080/reset-password

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  server:
    address: 127.0.0.1
    port: 8082
