spring:
  mvc.log-resolved-exception: false
  application:
    name: spring-ad-search
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO

# JWT configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000  # 1 hour in milliseconds
  issuer: spring-ad-search
  refresh-token:
    cookie-name: refresh-token
    expiration: 604800000  # 7 days in milliseconds

# Password reset configuration
password-reset:
  token-expiration: 86400000  # 24 hours in milliseconds
  base-url: ${BASE_URL}/password-reset
