name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x backend/gradlew
    
    - name: Build with Gradle
      run: cd backend && ./gradlew build -x test
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: backend/build/libs/*.jar
  
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    
    services:
      postgres:
        image: postgres:17.3
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      mailpit:
        image: axllent/mailpit:v1.23
        ports:
          - 1025:1025
          - 8025:8025
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x backend/gradlew
    
    - name: Run tests
      run: cd backend && ./gradlew test
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
        SPRING_DATASOURCE_USERNAME: ${{ secrets.TEST_DB_USER }}
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        SPRING_MAIL_HOST: localhost
        SPRING_MAIL_PORT: 1025
    
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports
        path: backend/build/reports/tests/
