name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  docker-image:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    outputs:
      version: ${{ steps.meta.outputs.version }}
      image-name: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}
          tags: |
            type=semver,pattern={{version}}-${{ matrix.arch }}
            type=raw,value=latest-${{ matrix.arch }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./devops/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Extract version
        id: version
        run: echo "tag=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create and push multiarch image
  
        run: |
          # Create multiarch manifest for version tag
            docker buildx imagetools create -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:${{ steps.version.outputs.tag }} \
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:${{ steps.version.outputs.tag }}-amd64 \
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:${{ steps.version.outputs.tag }}-arm64

          # Create multiarch manifest for latest tag
          docker buildx imagetools create -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:latest \
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:latest-amd64 \
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:latest-arm64

  deploy:
    runs-on: ubuntu-latest
    needs: docker-image
    container: alpine/ansible:2.18.6
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SERVER_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}

      - name: Create Ansible inventory
        working-directory: devops/ansible
        run: |
          cat > inventory.ini << EOF
          [raspberry]
          ${{ secrets.SERVER_HOST }} ansible_user=${{ secrets.SERVER_USERNAME }} ansible_ssh_private_key_file=~/.ssh/production.key
          EOF

      - name: Run ansible playbook
        working-directory: devops/ansible
        run: |
          ansible-playbook -i inventory.ini playbook/main.yml --ssh-extra-args='-o StrictHostKeyChecking=no'
        env:
          ANSIBLE_APP_NAME: ${{ secrets.APP_NAME }}
          ANSIBLE_MAIL_HOST: ${{ secrets.MAIL_HOST }}
          ANSIBLE_MAIL_PORT: ${{ secrets.MAIL_PORT }}
          ANSIBLE_MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          ANSIBLE_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          ANSIBLE_DB_HOST: ${{ secrets.DB_HOST }}
          ANSIBLE_DB_PORT: ${{ secrets.DB_PORT }}
          ANSIBLE_DB_NAME: ${{ secrets.DB_NAME }}
          ANSIBLE_DB_USERNAME: ${{ secrets.DB_USERNAME }}
          ANSIBLE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ANSIBLE_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ANSIBLE_BASE_URL: ${{ secrets.BASE_URL }}
          ANSIBLE_DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}:latest
          ANSIBLE_K3S_APP_PORT: ${{ secrets.K3S_APP_PORT }}
          ANSIBLE_K3S_REPLICAS: ${{ secrets.K3S_REPLICAS }}
          ANSIBLE_PG_VERSION: ${{ secrets.PG_VERSION }}
