name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  docker-image:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    outputs:
      version: ${{ steps.meta.outputs.version }}
      image-name: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}
          tags: |
            type=semver,pattern={{version}}-${{ matrix.arch }}
            type=raw,value=latest-${{ matrix.arch }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./devops/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  docker-multiarch-image:
    needs: docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version
        id: version
        run: echo "tag=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create and push multiarch image

        run: |
          # Create multiarch manifest for version tag
            docker buildx imagetools create -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:${{ steps.version.outputs.tag }} \
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:${{ steps.version.outputs.tag }}-amd64 \
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:${{ steps.version.outputs.tag }}-arm64

          # Create multiarch manifest for latest tag
          docker buildx imagetools create -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:latest \
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:latest-amd64 \
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:latest-arm64

  remove-monoarch-image:
    needs: docker-multiarch-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract version
        id: version
        run: echo "tag=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Install hub-tool
        run: |
          wget https://github.com/docker/hub-tool/releases/download/v0.4.6/hub-tool-linux-amd64.tar.gz -O hub-tool.tar.gz
          tar -xzf hub-tool.tar.gz
          chmod +x hub-tool/hub-tool
          sudo mv hub-tool/hub-tool /usr/local/bin/

      - name: Login hub-tool
        run: |
          HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"$DOCKER_USERNAME\", \"password\": \"$DOCKER_PASSWORD\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
          USERNAME="$(printf '%s:' "$DOCKER_USERNAME" | base64 -w0)"
          USER_PASS="$(printf '%s:%s' "$DOCKER_USERNAME" "$DOCKER_PASSWORD" | base64 -w0)"
          mkdir -p ~/.docker/
          printf '{"auths": {"hub-tool": {"auth": "%s"}, "hub-tool-refresh-token": {"auth": "%s"}, "hub-tool-token": { "auth": "%s", "identitytoken": "%s"}}}' \
            "$USER_PASS" "$USERNAME" \
            "$USERNAME" "$HUB_TOKEN" \
            > ~/.docker/config.json
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

      - name: Run hub-tool commands
        run: |
          hub-tool tag rm --verbose --force ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:${{ steps.version.outputs.tag }}-amd64
          hub-tool tag rm --verbose --force ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:${{ steps.version.outputs.tag }}-arm64
          hub-tool tag rm --verbose --force ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:latest-amd64
          hub-tool tag rm --verbose --force ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_IMAGE }}:latest-arm64

  deploy:
    runs-on: ubuntu-latest
    needs: remove-monoarch-image
    container: alpine/ansible:2.18.6
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SERVER_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}

      - name: Create Ansible inventory
        working-directory: devops/ansible
        run: |
          cat > inventory.ini << EOF
          [raspberry]
          ${{ secrets.SERVER_HOST }} ansible_user=${{ secrets.SERVER_USERNAME }} ansible_ssh_private_key_file=~/.ssh/production.key
          EOF

      - name: Run ansible playbook
        working-directory: devops/ansible
        run: |
          ansible-playbook -i inventory.ini playbook/main.yml --ssh-extra-args='-o StrictHostKeyChecking=no'
        env:
          ANSIBLE_APP_NAME: ${{ secrets.APP_NAME }}
          ANSIBLE_MAIL_HOST: ${{ secrets.MAIL_HOST }}
          ANSIBLE_MAIL_PORT: ${{ secrets.MAIL_PORT }}
          ANSIBLE_MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          ANSIBLE_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          ANSIBLE_DB_HOST: ${{ secrets.DB_HOST }}
          ANSIBLE_DB_PORT: ${{ secrets.DB_PORT }}
          ANSIBLE_DB_NAME: ${{ secrets.DB_NAME }}
          ANSIBLE_DB_USERNAME: ${{ secrets.DB_USERNAME }}
          ANSIBLE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ANSIBLE_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ANSIBLE_BASE_URL: ${{ secrets.BASE_URL }}
          ANSIBLE_DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}:latest
          ANSIBLE_K3S_APP_PORT: ${{ secrets.K3S_APP_PORT }}
          ANSIBLE_K3S_REPLICAS: ${{ secrets.K3S_REPLICAS }}
          ANSIBLE_PG_VERSION: ${{ secrets.PG_VERSION }}
